name: Pylint

on:
  workflow_dispatch:
  push:
    paths:
      - '*.py'
  pull_request:
    paths:
      - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install portaudio19-dev
        pip install -r ./requirements.txt
        pip install git+https://github.com/pylint-dev/pylint.git@main
    - name: Analysing the code with pylint
      run: |
       pylint $(git ls-files '*.py')
    # python-version: 3.11
    # changes made on 08.03.2025: want to see issue 10189 fixed as that one has been merged
    # once they release pylint 3.3.5, use pylint.yml
