name: Pylint yyybadge

on:
  workflow_dispatch:
  #push:
  #  paths:
  #    - '*.py'
  #pull_request:
  #  paths:
  #    - '*.py'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install portaudio19-dev
        pip install -r ./requirements.txt
    #    pip install pylint
    #- name: Analysing the code with pylint
    #  run: |
    #   pylint $(git ls-files '*.py')
    - name: Dynamic PyLint Badge connected with GitHub Artifact
      uses: YaoYinYing/pylint-github-action@v3.2
      with:
        lint-path: |
         - '*.py'
        python-version: 3.11  # python version which will lint the package
        #python-version: ${{ env.lint-python-version }}  # python version which will lint the package
        badge-text: pylint score
        #badge-file-name: pylint_scan
        #conda-env-name: my-package
